from .defs import Act

images = [
    Act(command=":images", sleep=3),
    Act(key="0"),
    Act(key="0"),
    Act(key="Page_Down"),
    Act(key="Page_Down"),
    Act(key="Escape"),
    Act(key="1", sleep=5),
    Act(key="Escape"),
    Act(key="2"),
    Act(key="Escape"),
    Act(key="3"),
    Act(key="0"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="Escape"),
    Act(key="Escape"),
    Act(key="4"),
    Act(key="0"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="plus"),
    Act(key="Escape"),
    Act(key="Escape"),
    Act(key="5", sleep=2),
    Act(key="Page_Down"),
    Act(key="Page_Down"),
    Act(key="Page_Down"),
    Act(key="Page_Down"),
    Act(key="Escape"),
    Act(key="Escape"),
    Act(key="Escape"),
]